/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        foreground: "var(--color-foreground)",
        primary: "var(--color-primary)",
        "primary-foreground": "var(--color-primary-foreground)",
        secondary: "var(--color-secondary)",
        "secondary-foreground": "var(--color-secondary-foreground)",
        muted: "var(--color-muted)",
        "muted-foreground": "var(--color-muted-foreground)",
        accent: "var(--color-accent)",
        "accent-foreground": "var(--color-accent-foreground)",
        card: "var(--color-card)",
        "card-foreground": "var(--color-card-foreground)",
        popover: "var(--color-popover)",
        "popover-foreground": "var(--color-popover-foreground)",
        border: "var(--color-border)",
        input: "var(--color-input)",
        ring: "var(--color-ring)",
        destructive: "var(--color-destructive)",
        "destructive-foreground": "var(--color-destructive-foreground)",
        success: "var(--color-success)",
        "success-foreground": "var(--color-success-foreground)",
        warning: "var(--color-warning)",
        "warning-foreground": "var(--color-warning-foreground)",
        info: "var(--color-info)",
        "info-foreground": "var(--color-info-foreground)",
      },
      fontSize: {
        xs: "var(--font-size-xs)",
        sm: "var(--font-size-sm)",
        base: "var(--font-size-base)",
        lg: "var(--font-size-lg)",
        xl: "var(--font-size-xl)",
        "2xl": "var(--font-size-2xl)",
        "3xl": "var(--font-size-3xl)",
        "4xl": "var(--font-size-4xl)",
        "5xl": "var(--font-size-5xl)",
      },
      lineHeight: {
        tight: "var(--line-height-tight)",
        snug: "var(--line-height-snug)",
        normal: "var(--line-height-normal)",
        relaxed: "var(--line-height-relaxed)",
        loose: "var(--line-height-loose)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        "3xl": "var(--radius-3xl)",
      },
      // animation: {
      //   "accordion-down": "var(--animate-accordion-down)",
      //   "accordion-up": "var(--animate-accordion-up)",
      // },
      typography: {
        DEFAULT: {
          css: {
            "--tw-prose-body": "var(--color-foreground)",
            "--tw-prose-headings": "var(--color-foreground)",
            "--tw-prose-lead": "var(--color-muted-foreground)",
            "--tw-prose-links": "var(--color-primary)",
            "--tw-prose-bold": "var(--color-foreground)",
            "--tw-prose-counters": "var(--color-muted-foreground)",
            "--tw-prose-bullets": "var(--color-muted-foreground)",
            "--tw-prose-hr": "var(--color-border)",
            "--tw-prose-quotes": "var(--color-foreground)",
            "--tw-prose-quote-borders": "var(--color-border)",
            "--tw-prose-captions": "var(--color-muted-foreground)",
            "--tw-prose-code": "var(--color-foreground)",
            "--tw-prose-pre-code": "var(--color-foreground)",
            "--tw-prose-pre-bg": "var(--color-muted)",
            "--tw-prose-th-borders": "var(--color-border)",
            "--tw-prose-td-borders": "var(--color-border)",

            // Dark mode
            "--tw-prose-invert-body": "var(--color-foreground)",
            "--tw-prose-invert-headings": "var(--color-foreground)",
            "--tw-prose-invert-lead": "var(--color-muted-foreground)",
            "--tw-prose-invert-links": "var(--color-primary)",
            "--tw-prose-invert-bold": "var(--color-foreground)",
            "--tw-prose-invert-counters": "var(--color-muted-foreground)",
            "--tw-prose-invert-bullets": "var(--color-muted-foreground)",
            "--tw-prose-invert-hr": "var(--color-border)",
            "--tw-prose-invert-quotes": "var(--color-foreground)",
            "--tw-prose-invert-quote-borders": "var(--color-border)",
            "--tw-prose-invert-captions": "var(--color-muted-foreground)",
            "--tw-prose-invert-code": "var(--color-foreground)",
            "--tw-prose-invert-pre-code": "var(--color-foreground)",
            "--tw-prose-invert-pre-bg": "var(--color-muted)",
            "--tw-prose-invert-th-borders": "var(--color-border)",
            "--tw-prose-invert-td-borders": "var(--color-border)",

            // Element-specific overrides
            a: {
              color: "var(--color-primary)",
              textDecoration: "underline",
              textDecorationOffset: "4px",
              fontWeight: "500",
              "&:hover": {
                color: "color-mix(in oklch, var(--color-primary), black 20%)",
              },
            },
            h1: {
              fontWeight: "700",
              fontSize: "var(--font-size-4xl)",
              lineHeight: "var(--line-height-tight)",
              letterSpacing: "-0.025em",
              marginBottom: "1.5rem",
            },
            h2: {
              fontWeight: "600",
              fontSize: "var(--font-size-3xl)",
              lineHeight: "var(--line-height-tight)",
              marginTop: "2rem",
              marginBottom: "1rem",
            },
            h3: {
              fontWeight: "600",
              fontSize: "var(--font-size-2xl)",
              lineHeight: "var(--line-height-snug)",
              marginTop: "1.5rem",
              marginBottom: "0.75rem",
            },
            h4: {
              fontWeight: "600",
              fontSize: "var(--font-size-xl)",
              lineHeight: "var(--line-height-snug)",
            },
            p: {
              lineHeight: "var(--line-height-relaxed)",
            },
            code: {
              color: "var(--color-foreground)",
              backgroundColor: "var(--color-muted)",
              fontWeight: "400",
              borderRadius: "0.25rem",
              padding: "0.125rem 0.25rem",
            },
            "code::before": {
              content: '""',
            },
            "code::after": {
              content: '""',
            },
            pre: {
              backgroundColor: "var(--color-muted)",
              borderRadius: "var(--radius-md)",
              padding: "1rem",
              overflowX: "auto",
            },
            hr: {
              borderColor: "var(--color-border)",
              marginTop: "2rem",
              marginBottom: "2rem",
            },
            table: {
              width: "100%",
              tableLayout: "auto",
              textAlign: "left",
              marginTop: "2rem",
              marginBottom: "2rem",
            },
            thead: {
              borderBottomWidth: "1px",
              borderBottomColor: "var(--color-border)",
            },
            "thead th": {
              fontWeight: "600",
              verticalAlign: "bottom",
              paddingBottom: "0.5rem",
              color: "var(--color-foreground)",
            },
            "tbody tr": {
              borderBottomWidth: "1px",
              borderBottomColor: "var(--color-border)",
            },
            "tbody tr:last-child": {
              borderBottomWidth: "0",
            },
            "tbody td": {
              verticalAlign: "baseline",
              paddingTop: "0.5rem",
              paddingBottom: "0.5rem",
            },
          },
        },
      },
      transitionDuration: {
        default: "var(--default-transition-duration)",
      },
      transitionTimingFunction: {
        default: "var(--default-transition-timing-function)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/forms"),
    require("tailwindcss-animate"),
  ],
  darkMode: "selector",
  // Optimize by disabling unused utilities
  corePlugins: {
    float: false,
    clear: false,
    skew: false,
    placeSelf: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    hueRotate: false,
    invert: false,
    sepia: false,
  },
  // Safety and sanitation
  future: {
    respectDefaultRingColorOpacity: true,
    disableColorOpacityUtilitiesByDefault: true,
    hoverOnlyWhenSupported: true,
  },
};
